### ISSUE TITLE
Question: How to analyze guppy heap files

### ISSUE THREAD

**Issue by satybald** [zhuyifei1999/guppy3#20]
Thank you for porting guppy to the latest and greatest Py3. I am wondering how to analyze guppy heap files that has been dump to files with some UI/console tools?

**Comment by zhuyifei1999** [comment]
Are you referring to https://zhuyifei1999.github.io/guppy3/heapy_UniSet.html#heapykinds.IdentitySet.dump ?

I think the dumps are in GSL (Guppy Specification Language) and is only used by Guppy Profile Browser. The data inside and the features of the browser is unfortunately quite lacking :/

**Comment by zhuyifei1999** [comment]
Anything else? Else I'm closing this.
