### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [zhuyifei1999/guppy3#29]
Problem
---------
On aarch64, pip install guppy3 builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install guppy3 should download the wheels from pypi

@zhuyifei1999 , Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by zhuyifei1999** [comment]
Fixed by #29

**Comment by zhuyifei1999** [comment]
Released. Wheels are built and published: https://pypi.org/project/guppy3/3.1.1/#files

Thanks for the PR!
