### ISSUE TITLE
Is it possible to dump the memory snapshot for offline analysis?

### ISSUE THREAD

**Issue by miniminiwhite** [zhuyifei1999/guppy3#33]
Hi,

I got this question after checking out #24 . 

In fact, I have some memory issues with my Django server, but the online environment is not quite reachable for some reason.

Therefore, I wonder whether guppy3 provides any approaches to dump the memory/heap snapshot so that I can retrieve the snapshot via an API and do the rest of the analysis offline.

Thanks.

**Comment by zhuyifei1999** [comment]
Unfortunately, not really :( Guppy can dump the statistics from an existing guppy session, but any 'more advanced' analysis, such as trying to filter by reference types, needs to be analyzed from within.

**Comment by zhuyifei1999** [comment]
> Guppy can dump the statistics from an existing guppy session

[IdentitySet.dump](https://zhuyifei1999.github.io/guppy3/heapy_UniSet.html#heapykinds.IdentitySet.dump) is the function.

```python
>>> import guppy
>>> guppy.hpy().heap().dump('test.hpy')
```

makes:

```
.loader: _load_stat
.format: SetFormat
.timemade: 1628756373.710652
.count: 38146
.size: 4497412
.kindname: 
.kindheader: Kind (class / dict of class)
.numrows: 127
.r: 11118 985591 str
.r: 7725 535840 tuple
.r: 576 480952 type
.r: 2668 471304 types.CodeType
.r: 5242 375945 bytes
.r: 2448 332928 function
[...]
.r: 1 16 builtins.NoneType
.r: 1 16 builtins.NotImplementedType
.r: 1 16 builtins.ellipsis
.end: .loader: _load_stat
```

... which you can get by `guppy.hpy().heap().all` (use repr() or str() to convert it to string)

**Comment by zhuyifei1999** [comment]
I'm gonna close this as dup of #22 and #24. Feel free to reopen if you have more questions.
